base:
  random_seed: 42
data:
  val_split: 0.15
training:
  n_trials: 40
  batch_size: 64
  epochs: 10
predict:
  model_name: nn-1
  model_version: 1
tracking_server:
  uri: http://localhost:8080
  experiment_name: mlops-workflow
model_params:
  svc:
    kernel: linear
    C: 0.22423877402195014
    max_iter: 1901
  nn:
    lr: 0.38745095611548397
    momentum: 0.6820577390413722
