data:
  val_split: 0.15
  random_seed: 42

training:
  n_trials: 40

predict:
  model_name: "nn-1"
  model_version: 3

model:
  svc:
    C: 0.64535
    kernel: "rbf"
    gamma: 0.0487
    degree: 1

  nn:
    lr: 0.231452
    momentum: 0.790705
